StudentHubCZ/thesishub

studenthub-portal/api-docs/swagger.json
studenthub-portal/src/main/java/cz/studenthub/core/Company.java
studenthub-portal/src/main/java/cz/studenthub/core/Faculty.java
studenthub-portal/src/main/java/cz/studenthub/core/Topic.java
studenthub-portal/src/main/java/cz/studenthub/core/TopicApplication.java
studenthub-portal/src/main/java/cz/studenthub/core/University.java
studenthub-portal/src/main/java/cz/studenthub/core/User.java
studenthub-portal/src/main/java/cz/studenthub/db/CompanyDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/FacultyDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/TopicApplicationDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/TopicDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/UniversityDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/UserDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.0.xml

* Added named query for every ManyToOne relation.
* Refactored many of the one letter variables.
* Added Creator field into Topic.
* Added ThesisStart field into TopicApplication.
* Updated migrations.

Added named query for every ManyToOne relation.

---

studenthub-portal/src/main/java/cz/studenthub/StudentHubApplication.java
studenthub-portal/src/main/java/cz/studenthub/core/TopicApplication.java
studenthub-portal/src/main/java/cz/studenthub/db/TopicApplicationDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/CompanyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/FacultyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TagResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UniversityResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UserResource.java

* Added endpoint for every ManyToOne relation.
* Added Tag resource for getting users and topics by tag.
* Refactored some variable names.
* **[GET] /api/topics** now supports paging.
This PR is dependent on #28.

Added endpoint for every ManyToOne relation

---

studenthub-portal/src/main/java/cz/studenthub/db/TopicDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java

* Added simple criteria for searching topics.
* Moved paging logic into its own function in TopicResource.
* In future should be probably done on Database level or at least moved to Util class.
* Added search endpoint for TopicResource with paging.

Add search functionality to Topic

---

studenthub-portal/src/main/java/cz/studenthub/resources/CompanyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/FacultyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UniversityResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UserResource.java

Update and Delete endpoints now check if id actually exists.

#27 - Delete and update endpoints throw error when non-existent id is supplied

---

pom.xml

Update Dropwizard to 1.1.0

---

studenthub-portal/src/main/java/cz/studenthub/StudentHubApplication.java
studenthub-portal/src/main/java/cz/studenthub/core/Task.java
studenthub-portal/src/main/java/cz/studenthub/db/TaskDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.0.xml
studenthub-portal/src/test/java/cz/studenthub/db/AbstractDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/TaskDAOTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml

* Added TODO functionality to TopicApplication.
* Includes also DAO test and updated migration script.

Add TODO to TopicApplication

---

studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java

* Updated permission checking in PUT endpoints in TopicApplicationResource and TopicResource, since no other resources are affected.

#48 - Update permission checks in PUT methods

---

studenthub-portal/src/main/java/cz/studenthub/core/Faculty.java
studenthub-portal/src/main/java/cz/studenthub/core/Task.java
studenthub-portal/src/main/java/cz/studenthub/core/TopicApplication.java
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.0.xml

All fields specified in #55 are now required.

#55 - Make more fields required in domain classes

---

studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java

* Removed automatically setting creator based on current user.
* Added permission check for when user tries to create/update topic with different creator than himself.

#60 - Topic creator has to be sent in a request body

---

studenthub-portal/src/main/java/cz/studenthub/db/FacultyDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/UniversityDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/CompanyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/FacultyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TagResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UniversityResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UserResource.java
studenthub-portal/src/main/java/cz/studenthub/util/PagingUtil.java

* Added two new endpoints **/university/search** and **/university/{id}/faculty/search**.
* Added search methods into UniversityDAO and FacultyDAO.
* Moved paging logic into its own PagingUtil class.
* Fixed #61 and #32.
* Start must be lower than size of collection. If bigger or equal it throws BAD_REQUEST. 
* Added paging functionality to all endpoint that returns list.
* It is purely optional.

#65 - Add search to UniversityResource

---

studenthub-portal/src/main/java/cz/studenthub/core/TopicGrade.java

* For situations when topic application is created but couldn't be finished.

#62 - Add NOT_FINISHED to TopicGrade

---

studenthub-portal/src/main/java/cz/studenthub/util/PagingUtil.java

#78 - Paging is now not calculated if list is empty

---

pom.xml
studenthub-portal/Dockerfile
studenthub-portal/pom.xml
studenthub-portal/src/main/resources/docker/start.sh

Added two new profiles to `pom.xml`:
1. `docker` which builds docker image from supplied Dockerfile.
* Based on `openjdk:8-jre-alpine`, `openjdk` because it if officially supported and `alpine` to make it as lightweight as possible.
* Inside it is script which takes either run the server (`run`), runs migrations (`migrate`) or both (`start`) and can even pass arguments straight to the jar file.
2. `swagger` which generates swagger documentation.

#42 - Create automatically Docker image 

---

studenthub-portal/src/main/java/cz/studenthub/core/Topic.java
studenthub-portal/src/main/java/cz/studenthub/db/TopicDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.0.xml
studenthub-portal/src/test/java/cz/studenthub/db/CompanyDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/TopicDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/UserResourceTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml

* Added `enabled` field into Topic.
* It is set to `true` by default.
* Updated endpoints to include (or not include) disabled topics based on #67.
* Added search test into TopicDAOTest.

#67 - Add enabled field into Topic

---

studenthub-portal/src/main/java/cz/studenthub/resources/CompanyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/FacultyResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/LoginResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TagResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TaskResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UniversityResource.java
studenthub-portal/src/main/java/cz/studenthub/resources/UserResource.java
studenthub-portal/src/main/resources/config.yml

* Added metric annotations to resource endpoints.
* @Timed to every endpoint that returns List, which measures time that it took to complete request.
* @ExceptionMetered to every PUT,POST,DELETE endpoint, which measures number of exceptions.
* Added default admin page http://localhost:8081/info where all metrics, healthchecks etc are available.
* Since only 8080 will be opened on production server, it shouldn't cause any problems.

#40 - Add metric annotations to endpoints

---

studenthub-portal/src/test/java/cz/studenthub/IntegrationTestSuite.java
studenthub-portal/src/test/java/cz/studenthub/integration/CompanyResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/FacultyResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/LoginResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TagResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TaskResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicApplicationResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/UniversityResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/UserResourceTest.java

* From 500ms to 1s.
* It ran 5 times without any error on my 512 MB virtual machine, so hopefully it will run also on travis (fingers crossed).

Increase timeout in Integration tests

---

studenthub-portal/initial-data.xml
studenthub-portal/seed.sql
studenthub-portal/src/main/resources/db/InitialData.md
studenthub-portal/src/test/resources/db/DB.md

* Added basic configuration with few user, admin etc.
* Removed seed.sql file since it is no longer needed.

Add initial data migration

---

studenthub-portal/initial-data.xml
studenthub-portal/src/main/java/cz/studenthub/core/Topic.java
studenthub-portal/src/main/resources/db/InitialData.md
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.0.xml
studenthub-portal/src/test/java/cz/studenthub/db/TopicDAOTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml

* Added secondaryDescription field into Topic.
* Updated TestDB and InitialDB configurations to reflect the change.

#93 - Add secondaryDescription field into Topic

---

studenthub-portal/initial-data.xml
studenthub-portal/src/main/java/cz/studenthub/core/Topic.java
studenthub-portal/src/main/resources/db/InitialData.md
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.1.xml
studenthub-portal/src/main/resources/migrations.xml
studenthub-portal/src/test/java/cz/studenthub/db/TopicDAOTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml

* Added secondaryTitle field into Topic
* Updated InitialDB and TestDB to reflect this change.
* Since 1.0 is out, I created new changelog file and made changes there.

#105 - Add secondaryTitle into Topic

---

README.md
studenthub-portal/src/main/java/cz/studenthub/StudentHubApplication.java
studenthub-portal/src/main/java/cz/studenthub/StudentHubConfiguration.java
studenthub-portal/src/main/resources/config.yml

* Usage of BasicAuth is now configurable in configuration file.
* Default value is false.
* Order of authorization is still same, first it will look into cookie then anything else.
* Updated README to include list of all environment variables.
* Replaced EXAMPLE column with DEFAULT_VALUE column.

#108 - Usage is of BasicAuth is now configurable

---

pom.xml
studenthub-portal/pom.xml
studenthub-portal/src/main/java/cz/studenthub/resources/RegistrationResource.java
studenthub-portal/src/main/java/cz/studenthub/util/MailClient.java
studenthub-portal/src/main/java/cz/studenthub/util/SmtpConfig.java
studenthub-portal/src/test/java/cz/studenthub/IntegrationTestSuite.java
studenthub-portal/src/test/java/cz/studenthub/integration/CompanyResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/FacultyResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/LoginResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/RegistrationResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TagResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TaskResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicApplicationResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/UniversityResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/UserResourceTest.java
studenthub-portal/src/test/resources/config-test.yml
studenthub-portal/src/test/resources/db/test-data.xml
studenthub-portal/src/test/resources/testng.xml

* Added RegistrationResourceTest.
* Tests almost everything I could think of including some basic testing of templates them selfs.
* Added GreenMail as dependency since is servers as SMTP server mock.
* Fixed weird modifer in Integration tests.
* Removed static and made everything private.
* Fixed `account/{id}/password` bug, where is updated password for the wrong user.
* Updated dependency for TaskResourceTest.

#86 - Add RegistrationResourceTest

---

studenthub-ui/src/Translations.js
studenthub-ui/src/components/DeleteButton.js

Add confirmation dialog on delete button press

---

studenthub-ui/src/views/Application.js
studenthub-ui/src/views/TopicSearch.js

Application dates and leader/supervisor editation corrections

---

studenthub-portal/src/test/java/cz/studenthub/integration/RegistrationResourceTest.java

* Fixed timeout error in RegistrationResourceTest.

Fix timeout error in RegistrationResourceTest

---

studenthub-ui/src/App.js
studenthub-ui/src/Translations.js
studenthub-ui/src/components/TopicDetailsDialog.js
studenthub-ui/src/views/MyTopics.js
studenthub-ui/src/views/Topic.js

Create unique topic preview URL page

---

studenthub-ui/src/Translations.js
studenthub-ui/src/Util.js
studenthub-ui/src/components/ContentTable.js
studenthub-ui/src/components/Pager.js
studenthub-ui/src/views/MyApplications.js
studenthub-ui/src/views/MyTopics.js
studenthub-ui/src/views/TopicSearch.js
studenthub-ui/src/views/Users.js

Add paging support

---

studenthub-ui/src/App.js
studenthub-ui/src/Translations.js
studenthub-ui/src/Util.js
studenthub-ui/src/views/Companies.js
studenthub-ui/src/views/CompanyPlans.js
studenthub-ui/src/views/CompanyReg.js
studenthub-ui/src/views/Profile.js

Fixes points 5 and 7 of #115 and maybe even #98 (Plan editation added to company tab in profile view, there is no upgrade request though, just straight plan out editation.)
POST, PUT and DELETE requests do not work yet (#162, #163).

Add companies management and registration

---

studenthub-portal/initial-data.xml
studenthub-portal/src/main/java/cz/studenthub/core/TopicApplication.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicApplicationResource.java
studenthub-portal/src/main/resources/db/InitialData.md
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.1.xml
studenthub-portal/src/test/java/cz/studenthub/db/TopicApplicationDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicApplicationResourceTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml
studenthub-ui/src/Translations.js
studenthub-ui/src/views/Application.js
studenthub-ui/src/views/MyApplications.js

* Added `link` field into TopicApplication.
* This field is validated by `@Url`, which means that it **needs** to have protocol specified.
* Length of field is limited to 2000, since that is the value that is will 100% work on every configuration.
* Updated wrongly named setter and getter for field `thesisStart`.

#161 - Add link into TopicApplication

---

studenthub-portal/initial-data.xml
studenthub-portal/src/main/java/cz/studenthub/StudentHubApplication.java
studenthub-portal/src/main/java/cz/studenthub/api/DAOBinder.java
studenthub-portal/src/main/java/cz/studenthub/core/Topic.java
studenthub-portal/src/main/java/cz/studenthub/core/TopicApplication.java
studenthub-portal/src/main/java/cz/studenthub/core/TopicDegree.java
studenthub-portal/src/main/java/cz/studenthub/db/TaskDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/TopicDegreeDAO.java
studenthub-portal/src/main/java/cz/studenthub/db/UserDAO.java
studenthub-portal/src/main/java/cz/studenthub/resources/TopicDegreeResource.java
studenthub-portal/src/main/resources/db/changelog/db.changelog-1.1.xml
studenthub-portal/src/test/java/cz/studenthub/DAOTestSuite.java
studenthub-portal/src/test/java/cz/studenthub/db/CompanyPlanDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/ProjectDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/TopicApplicationDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/TopicDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/db/TopicDegreeDAOTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/CompanyPlanResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicApplicationResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicDegreeResourceTest.java
studenthub-portal/src/test/java/cz/studenthub/integration/TopicResourceTest.java
studenthub-portal/src/test/resources/db/DB.md
studenthub-portal/src/test/resources/db/test-data.xml
studenthub-portal/src/test/resources/testng.xml
studenthub-ui/src/App.js
studenthub-ui/src/Translations.js
studenthub-ui/src/views/Application.js
studenthub-ui/src/views/MyTopics.js
studenthub-ui/src/views/TopicDegrees.js

* TopicDegree is now domain class instead of enum.
* Hibernate named associated tables differently (`topic_degrees` -> `topics_degrees`), so I renamed the table to fit it.
*  Added `TopicDegreeDAO`, `TopicDegreeResource` and tests as well.
* Small refactor of variable names in DAO classes.
* Updated DB configurations to reflect these changes.

#114 - Make TopicDegree configurable

---

pom.xml
thesishub-application/pom.xml
thesishub-application/src/main/java/net/thesishub/core/Activation.java
thesishub-application/src/main/java/net/thesishub/core/Company.java
thesishub-application/src/main/java/net/thesishub/core/Faculty.java
thesishub-application/src/main/java/net/thesishub/core/GenericEntity.java
thesishub-application/src/main/java/net/thesishub/core/Project.java
thesishub-application/src/main/java/net/thesishub/core/Task.java
thesishub-application/src/main/java/net/thesishub/core/Topic.java
thesishub-application/src/main/java/net/thesishub/core/TopicApplication.java
thesishub-application/src/main/java/net/thesishub/core/University.java
thesishub-application/src/main/java/net/thesishub/core/User.java
thesishub-application/src/main/java/net/thesishub/resources/CompanyResource.java
thesishub-application/src/main/java/net/thesishub/resources/FacultyResource.java
thesishub-application/src/main/java/net/thesishub/resources/ProjectResource.java
thesishub-application/src/main/java/net/thesishub/resources/RegistrationResource.java
thesishub-application/src/main/java/net/thesishub/resources/TaskResource.java
thesishub-application/src/main/java/net/thesishub/resources/TopicApplicationResource.java
thesishub-application/src/main/java/net/thesishub/resources/TopicResource.java
thesishub-application/src/main/java/net/thesishub/resources/UniversityResource.java
thesishub-application/src/main/java/net/thesishub/resources/UserResource.java
thesishub-application/src/main/java/net/thesishub/util/Equals.java
thesishub-application/src/test/java/net/thesishub/UtilTestSuite.java
thesishub-application/src/test/java/net/thesishub/util/EqualsTest.java
thesishub-application/src/test/java/net/thesishub/util/PagingUtilTest.java

* User now cannot update his own company and faculty (unless he is admin)
* Added `EqualUti`l which is helper class for checking equal entities.
* Because of this I created common predecessor for entity classes  `GenericEntity`.
* It is not used in entities which have String ID, because of annotations.
* Added Unit tests for Util classes
* Maven now correctly executes jUnit tests.

#183 - User now cannot update his own company and faculty

---

thesishub-application/initial-data.xml
thesishub-application/src/main/java/net/thesishub/core/Topic.java
thesishub-application/src/main/java/net/thesishub/db/TopicDAO.java
thesishub-application/src/main/java/net/thesishub/resources/TopicResource.java
thesishub-application/src/main/resources/db/InitialData.md
thesishub-application/src/main/resources/db/changelog/db.changelog-1.1.xml
thesishub-application/src/test/java/net/thesishub/db/TopicDAOTest.java
thesishub-application/src/test/java/net/thesishub/integration/TopicResourceTest.java
thesishub-application/src/test/resources/db/DB.md
thesishub-application/src/test/resources/db/test-data.xml

* Add `highlighted` and `dateCreated` fields into `Topic`.
* Add endpoints `topics/highlighted` and `topics/recent`.
* Both take query arguments count, which defaults to 5.
* `topics/highlighted` also return random entries.

#192 - Add highlighted and dateCreated field into Topic

---

thesishub-application/src/main/java/net/thesishub/db/TopicDAO.java
thesishub-application/src/main/java/net/thesishub/resources/TopicResource.java
thesishub-application/src/test/java/net/thesishub/db/TopicDAOTest.java

* Tags are now properly fetched when searching.
* Added option to search to filter by degrees and companies.

Tags are now properly fetched when searching
